# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

demo_user = User.create(username: "DemoUser", email: "IAmTheBestDemoUser@demo.com", password: "DemoPassword", status: "Online")
user1 = User.create(username: "Tracer", email: "tracer@gmail.com", password: "password", status: "Offline")
user2 = User.create(username: "Junkrat", email: "junkrat@gmail.com", password: "password", status: "Offline")
user3 = User.create(username: "Mei", email: "mei@gmail.com", password: "password", status: "Offline")
user4 = User.create(username: "Winston", email: "winston@gmail.com", password: "password", status: "Offline")
user5 = User.create(username: "Reaper", email: "reaper@gmail.com", password: "password", status: "Offline")
user6 = User.create(username: "Hanzo", email: "hanzo@gmail.com", password: "password", status: "Offline")
user7 = User.create(username: "Genji", email: "genji@gmail.com", password: "password", status: "Offline")
user8 = User.create(username: "McCree", email: "mccree@gmail.com", password: "password", status: "Offline")
user9 = User.create(username: "I'm always away!", email: "incrediblylongemail123@gmail.com", password: "passwordpassword", status: "Away")

server1 = Server.create(name: "Overwatch", owner_id: user1.id)
server2 = Server.create(name: "Shimada", owner_id: user6.id)
server3 = Server.create(name: "DemoUser's Spectacular Server", owner_id: demo_user.id)
server4 = Server.create(name: "DM 1 and 2")
server5 = Server.create(name: "DM 1 and 8")
server6 = Server.create(name: "DM 1 and 9")

affiliation1 = Affiliation.create(user_id: demo_user.id, server_id: server1.id)
affiliation2 = Affiliation.create(user_id: user1.id, server_id: server1.id)
affiliation3 = Affiliation.create(user_id: user2.id, server_id: server1.id)
affiliation4 = Affiliation.create(user_id: user3.id, server_id: server1.id)
affiliation5 = Affiliation.create(user_id: user4.id, server_id: server1.id)
affiliation6 = Affiliation.create(user_id: user5.id, server_id: server1.id)
affiliation7 = Affiliation.create(user_id: demo_user.id, server_id: server2.id)
affiliation8 = Affiliation.create(user_id: user6.id, server_id: server2.id)
affiliation9 = Affiliation.create(user_id: user7.id, server_id: server2.id)
affiliation10 = Affiliation.create(user_id: user8.id, server_id: server2.id)
affiliation11 = Affiliation.create(user_id: demo_user.id, server_id: server3.id)

affiliation12 = Affiliation.create(user_id: demo_user.id, server_id: server4.id)
affiliation13 = Affiliation.create(user_id: user1.id, server_id: server4.id)
affiliation14 = Affiliation.create(user_id: demo_user.id, server_id: server5.id)
affiliation15 = Affiliation.create(user_id: user7.id, server_id: server5.id)
affiliation16 = Affiliation.create(user_id: demo_user.id, server_id: server6.id)
affiliation17 = Affiliation.create(user_id: user8.id, server_id: server6.id)

channel1 = Channel.create(name: "General", server_id: server1.id)
channel2 = Channel.create(name: "Party Time!", server_id: server1.id)
channel3 = Channel.create(name: "Hanamura", server_id: server2.id)
channel4 = Channel.create(name: "General", server_id: server3.id)

message1 = Message.create(body: "G'day, mate.", author_id: user2.id)
message2 = Message.create(body: "Cheers, love! The cavalry's-", author_id: user1.id)
message3 = Message.create(body: "Cheers, MATE! The cavalry's here!", author_id: user2.id)
message4 = Message.create(body: "That's my line!", author_id: user1.id)
message5 = Message.create(body: "No idea what ya' sayin' mate.", author_id: user2.id)
message6 = Message.create(body: "Don't be daft.", author_id: user1.id)
message7 = Message.create(body: "I don't know anything you're talking about!", author_id: user2.id)
message8 = Message.create(body: "You're just a no-good bully Junkrat. How can you even look at yourself in the mirror?", author_id: user3.id)
message9 = Message.create(body: "That's cold.", author_id: user2.id)
message57 = Message.create(body: "Brrr. I get cold just looking at ya.", author_id: user2.id)
message10 = Message.create(body: "You're terrible.", author_id: user3.id)
message11 = Message.create(body: "Well that just happened.", author_id: user1.id)

channel_message1 = ChannelMessage.create(message_id: message1.id, channel_id: channel1.id)
channel_message2 = ChannelMessage.create(message_id: message2.id, channel_id: channel1.id)
channel_message3 = ChannelMessage.create(message_id: message3.id, channel_id: channel1.id)
channel_message4 = ChannelMessage.create(message_id: message4.id, channel_id: channel1.id)
channel_message5 = ChannelMessage.create(message_id: message5.id, channel_id: channel1.id)
channel_message6 = ChannelMessage.create(message_id: message6.id, channel_id: channel1.id)
channel_message7 = ChannelMessage.create(message_id: message7.id, channel_id: channel1.id)
channel_message8 = ChannelMessage.create(message_id: message8.id, channel_id: channel1.id)
channel_message38 = ChannelMessage.create(message_id: message57.id, channel_id: channel1.id)
channel_message9 = ChannelMessage.create(message_id: message9.id, channel_id: channel1.id)
channel_message10 = ChannelMessage.create(message_id: message10.id, channel_id: channel1.id)
channel_message11 = ChannelMessage.create(message_id: message11.id, channel_id: channel1.id)

message12 = Message.create(body: "Party mode engaged!", author_id: user4.id)
message13 = Message.create(body: "Oh, Winston! *giggles* Got your favorite!", author_id: user1.id)
message14 = Message.create(body: "For the last time, no more bananas!", author_id: user4.id)
message15 = Message.create(body: "Winston! You're an animal! *giggles*", author_id: user1.id)
message16 = Message.create(body: "Empirical evidence suggests I'm a real animal.", author_id: user4.id)
message17 = Message.create(body: "Poor Winston. Has to hide away so he doesn't scare the children.", author_id: user5.id)
message56 = Message.create(body: "I don't even think children are afraid of you.", author_id: user4.id)
message18 = Message.create(body: "'Death comes!' *giggles*", author_id: user1.id)
message19 = Message.create(body: "You can't be serious.", author_id: user5.id)
message20 = Message.create(body: "Why so serious?", author_id: user2.id)

channel_message12 = ChannelMessage.create(message_id: message12.id, channel_id: channel2.id)
channel_message13 = ChannelMessage.create(message_id: message13.id, channel_id: channel2.id)
channel_message14 = ChannelMessage.create(message_id: message14.id, channel_id: channel2.id)
channel_message15 = ChannelMessage.create(message_id: message15.id, channel_id: channel2.id)
channel_message16 = ChannelMessage.create(message_id: message16.id, channel_id: channel2.id)
channel_message17 = ChannelMessage.create(message_id: message17.id, channel_id: channel2.id)
channel_message37 = ChannelMessage.create(message_id: message56.id, channel_id: channel2.id)
channel_message18 = ChannelMessage.create(message_id: message18.id, channel_id: channel2.id)
channel_message19 = ChannelMessage.create(message_id: message19.id, channel_id: channel2.id)
channel_message20 = ChannelMessage.create(message_id: message20.id, channel_id: channel2.id)

message21 = Message.create(body: "What's wrong, Hanzo? Don't you recognize me?", author_id: user7.id)
message22 = Message.create(body: "You may call yourself my brother, but you are not the Genji I knew.", author_id: user6.id)
message23 = Message.create(body: "It is not too late to change your course, brother.", author_id: user7.id)
message24 = Message.create(body: "You are mistaken, brother. I am beyond redemption.", author_id: user6.id)
message25 = Message.create(body: "So this is what has become of you? A pity.", author_id: user7.id)
message26 = Message.create(body: "i will not be judged by you.", author_id: user6.id)
message27 = Message.create(body: "You will never amount to anything!", author_id: user6.id)
message28 = Message.create(body: "We shall see, brother.", author_id: user7.id)
message29 = Message.create(body: "Think you can do better than me?", author_id: user6.id)
message30 = Message.create(body: "I am certain of it.", author_id: user7.id)
message31 = Message.create(body: "Ryūjin no ken wo kurae!", author_id: user7.id)
message32 = Message.create(body: "Ryū ga waga teki wo kurau!", author_id: user6.id)
message33 = Message.create(body: "Omae wa mou shindeiru.", author_id: user8.id)
message34 = Message.create(body: "NANI?", author_id: user6.id)
message35 = Message.create(body: "NANI?", author_id: user7.id)
message36 = Message.create(body: "It's high noon.", author_id: user8.id)

channel_message21 = ChannelMessage.create(message_id: message21.id, channel_id: channel3.id)
channel_message22 = ChannelMessage.create(message_id: message22.id, channel_id: channel3.id)
channel_message23 = ChannelMessage.create(message_id: message23.id, channel_id: channel3.id)
channel_message24 = ChannelMessage.create(message_id: message24.id, channel_id: channel3.id)
channel_message25 = ChannelMessage.create(message_id: message25.id, channel_id: channel3.id)
channel_message26 = ChannelMessage.create(message_id: message26.id, channel_id: channel3.id)
channel_message27 = ChannelMessage.create(message_id: message27.id, channel_id: channel3.id)
channel_message28 = ChannelMessage.create(message_id: message28.id, channel_id: channel3.id)
channel_message29 = ChannelMessage.create(message_id: message29.id, channel_id: channel3.id)
channel_message30 = ChannelMessage.create(message_id: message30.id, channel_id: channel3.id)
channel_message31 = ChannelMessage.create(message_id: message31.id, channel_id: channel3.id)
channel_message32 = ChannelMessage.create(message_id: message32.id, channel_id: channel3.id)
channel_message33 = ChannelMessage.create(message_id: message33.id, channel_id: channel3.id)
channel_message34 = ChannelMessage.create(message_id: message34.id, channel_id: channel3.id)
channel_message35 = ChannelMessage.create(message_id: message35.id, channel_id: channel3.id)
channel_message36 = ChannelMessage.create(message_id: message36.id, channel_id: channel3.id)

message37 = Message.create(body: "Hi Tracer!", author_id: demo_user.id)
message38 = Message.create(body: "Heya!", author_id: user1.id)
message39 = Message.create(body: "I'm a big fan of yours! You're awesome!", author_id: demo_user.id)
message40 = Message.create(body: "Aww, thanks love!", author_id: user1.id)
message41 = Message.create(body: "I always wanted to be a hero just like you!", author_id: demo_user.id)
message42 = Message.create(body: "The world could always use more heroes.", author_id: user1.id)
message43 = Message.create(body: "I agree! So what's it like to b-", author_id: demo_user.id)
message44 = Message.create(body: "Wait a minute. How come it feels like I had this conversation before.", author_id: demo_user.id)
message45 = Message.create(body: "Ever get that feeling of déjà vu?", author_id: user1.id)

direct_message1 = DirectMessage.create(message_id: message37.id, server_id: server4.id)
direct_message2 = DirectMessage.create(message_id: message38.id, server_id: server4.id)
direct_message3 = DirectMessage.create(message_id: message39.id, server_id: server4.id)
direct_message4 = DirectMessage.create(message_id: message40.id, server_id: server4.id)
direct_message5 = DirectMessage.create(message_id: message41.id, server_id: server4.id)
direct_message6 = DirectMessage.create(message_id: message42.id, server_id: server4.id)
direct_message7 = DirectMessage.create(message_id: message43.id, server_id: server4.id)
direct_message8 = DirectMessage.create(message_id: message44.id, server_id: server4.id)
direct_message9 = DirectMessage.create(message_id: message45.id, server_id: server4.id)

message46 = Message.create(body: "Mi o sutete mo, myōri wa sutezu.", author_id: user7.id)
message47 = Message.create(body: "What does that mean?", author_id: demo_user.id)
message48 = Message.create(body: "Rin. Byō. Tō. Sha. Kai. Jin. Retsu. Zai. Zen.", author_id: user7.id)
message49 = Message.create(body: "Genji, please! I don't understand what you are saying!", author_id: demo_user.id)
message50 = Message.create(body: "Hitoshirezu kami no yurushi o machi shima ni, kokora tsure naki yo o sugusu ka na.", author_id: user7.id)
message51 = Message.create(body: "Genji, let's talk in english instead!!! Something that I can understand!?", author_id: demo_user.id)
message52 = Message.create(body: "I need healing.", author_id: user7.id)
message53 = Message.create(body: "*facepalm*", author_id: demo_user.id)

direct_message10 = DirectMessage.create(message_id: message46.id, server_id: server5.id)
direct_message11 = DirectMessage.create(message_id: message47.id, server_id: server5.id)
direct_message12 = DirectMessage.create(message_id: message48.id, server_id: server5.id)
direct_message13 = DirectMessage.create(message_id: message49.id, server_id: server5.id)
direct_message14 = DirectMessage.create(message_id: message50.id, server_id: server5.id)
direct_message15 = DirectMessage.create(message_id: message51.id, server_id: server5.id)
direct_message16 = DirectMessage.create(message_id: message52.id, server_id: server5.id)
direct_message17 = DirectMessage.create(message_id: message53.id, server_id: server5.id)

message54 = Message.create(body: "You do realize it's not really noon right now.", author_id: demo_user.id)
message55 = Message.create(body: "Well, it's high noon somewhere in the world.", author_id: user8.id)

direct_message18 = DirectMessage.create(message_id: message54.id, server_id: server6.id)
direct_message19 = DirectMessage.create(message_id: message55.id, server_id: server6.id)

friend1 = Friend.create(user_id_1: demo_user.id, user_id_2: user1.id)
friend2 = Friend.create(user_id_1: demo_user.id, user_id_2: user2.id)
friend3 = Friend.create(user_id_1: demo_user.id, user_id_2: user3.id)
friend4 = Friend.create(user_id_1: demo_user.id, user_id_2: user4.id)
friend5 = Friend.create(user_id_1: demo_user.id, user_id_2: user5.id)
friend6 = Friend.create(user_id_1: demo_user.id, user_id_2: user6.id)
friend7 = Friend.create(user_id_1: demo_user.id, user_id_2: user7.id)
friend8 = Friend.create(user_id_1: demo_user.id, user_id_2: user8.id)

friend9 = Friend.create(user_id_1: user1.id, user_id_2: demo_user.id)
friend10 = Friend.create(user_id_1: user2.id, user_id_2: demo_user.id)
friend11 = Friend.create(user_id_1: user3.id, user_id_2: demo_user.id)
friend12 = Friend.create(user_id_1: user4.id, user_id_2: demo_user.id)
friend13 = Friend.create(user_id_1: user5.id, user_id_2: demo_user.id)
friend14 = Friend.create(user_id_1: user6.id, user_id_2: demo_user.id)
friend15 = Friend.create(user_id_1: user7.id, user_id_2: demo_user.id)
friend16 = Friend.create(user_id_1: user8.id, user_id_2: demo_user.id)

friend17 = Friend.create(user_id_1: demo_user.id, user_id_2: user9.id)
friend18 = Friend.create(user_id_1: user9.id, user_id_2: demo_user.id)
